name: Update README.md?
on:
  push:
    branches: [main, master]
    paths:
      - '.github/templates/*'
      - '.github/workflows/*'
      - 'img/*'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: jmpa-io/depot/.github/workflows/README.yml@main
    secrets:
      github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      slack-webhook: ${{ secrets.SLACK_GITHUB_WEBHOOK_URL }}
